linters:
  disable-all: true
  enable:
    - gosec         # Detects security problems.
    - gofmt
    - goimports
    - gocritic      # Metalinter; detects bugs, performance, and styling issues.
    - gofumpt       # Detects whether code was gofumpt-ed.


linters-settings:



issues:

