package model

import "context"

// Code generated by go-swagger; DO NOT EDIT.

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// JSONAtlasStruct AtlasStruct
//
// Captures details of struct contents. Not instantiated directly, used only via AtlasEntity, AtlasClassification.
// Example: {"attributes":{"property1":{},"property2":{}},"typeName":"..."}
//
// swagger:model json_AtlasStruct
type JSONAtlasStruct struct {

	// attributes
	Attributes map[string]interface{} `json:"attributes,omitempty"`

	// type name
	TypeName string `json:"typeName,omitempty"`
}

// Validate validates this json atlas struct
func (m *JSONAtlasStruct) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this json atlas struct based on context it is used
func (m *JSONAtlasStruct) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *JSONAtlasStruct) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *JSONAtlasStruct) UnmarshalBinary(b []byte) error {
	var res JSONAtlasStruct
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
